// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NehasBeed.Data;

#nullable disable

namespace NehasBeed.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260718164935_AddStockAndNotifications")]
    partial class AddStockAndNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NehasBeed.Models.AdminNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminNotifications");
                });

            modelBuilder.Entity("NehasBeed.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NehasBeed.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "London",
                            Country = "United Kingdom",
                            CreatedAt = new DateTime(2026, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "sophia@example.com",
                            CustomerName = "Sophia Loren",
                            CustomerPhone = "+44 7700 900001",
                            InvoiceNumber = "NB-10001",
                            PaymentMethod = "Card",
                            Postcode = "SW1A 1AA",
                            ShippingAddress = "123 Luxury Lane",
                            ShippingCost = 0m,
                            Status = "Confirmed",
                            Subtotal = 185.00m,
                            TotalAmount = 185.00m,
                            UpdatedAt = new DateTime(2026, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            City = "Monaco",
                            Country = "Monaco",
                            CreatedAt = new DateTime(2026, 7, 14, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "grace@example.com",
                            CustomerName = "Grace Kelly",
                            CustomerPhone = "+377 99 99 00 00",
                            InvoiceNumber = "NB-10002",
                            PaymentMethod = "PayPal",
                            Postcode = "98000",
                            ShippingAddress = "Palace Avenue",
                            ShippingCost = 12.00m,
                            Status = "Dispatched",
                            Subtotal = 210.00m,
                            TotalAmount = 222.00m,
                            UpdatedAt = new DateTime(2026, 7, 14, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            City = "Dubai",
                            Country = "UAE",
                            CreatedAt = new DateTime(2026, 7, 17, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "zara@example.com",
                            CustomerName = "Zara Ahmed",
                            CustomerPhone = "+971 50 000 0000",
                            InvoiceNumber = "NB-10003",
                            PaymentMethod = "Card",
                            Postcode = "00000",
                            ShippingAddress = "Sheikh Zayed Road",
                            ShippingCost = 0m,
                            Status = "Pending",
                            Subtotal = 120.00m,
                            TotalAmount = 120.00m,
                            UpdatedAt = new DateTime(2026, 7, 17, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            City = "Milan",
                            Country = "Italy",
                            CreatedAt = new DateTime(2026, 7, 13, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "maria@example.com",
                            CustomerName = "Maria Rossi",
                            CustomerPhone = "+39 02 0000000",
                            InvoiceNumber = "NB-10004",
                            PaymentMethod = "Card",
                            Postcode = "20121",
                            ShippingAddress = "Via della Moda 5",
                            ShippingCost = 0m,
                            Status = "Rejected",
                            Subtotal = 145.00m,
                            TotalAmount = 145.00m,
                            UpdatedAt = new DateTime(2026, 7, 13, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            City = "Berlin",
                            Country = "Germany",
                            CreatedAt = new DateTime(2026, 7, 12, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "lena@example.com",
                            CustomerName = "Lena Böhm",
                            CustomerPhone = "+49 30 00000000",
                            InvoiceNumber = "NB-10005",
                            PaymentMethod = "Card",
                            Postcode = "10719",
                            ShippingAddress = "Kurfürstendamm 10",
                            ShippingCost = 12.00m,
                            Status = "Confirmed",
                            Subtotal = 165.00m,
                            TotalAmount = 177.00m,
                            UpdatedAt = new DateTime(2026, 7, 12, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NehasBeed.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SelectedColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            ProductImage = "images/bag-1.png",
                            ProductName = "Mosaic Tote",
                            Quantity = 1,
                            SelectedColor = "Multicolor",
                            UnitPrice = 185.00m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 2,
                            ProductId = 4,
                            ProductImage = "images/bag-4.png",
                            ProductName = "Pearl Mini",
                            Quantity = 1,
                            SelectedColor = "Pearl White",
                            UnitPrice = 210.00m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 3,
                            ProductId = 6,
                            ProductImage = "images/bag-3.png",
                            ProductName = "Sovereign Chain",
                            Quantity = 1,
                            SelectedColor = "Gold",
                            UnitPrice = 85.00m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 3,
                            ProductId = 7,
                            ProductImage = "images/bag-1.png",
                            ProductName = "Onyx Layers",
                            Quantity = 1,
                            SelectedColor = "Onyx Black",
                            UnitPrice = 35.00m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 4,
                            ProductId = 3,
                            ProductImage = "images/bag-3.png",
                            ProductName = "Noir Clutch",
                            Quantity = 1,
                            SelectedColor = "Black",
                            UnitPrice = 145.00m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 5,
                            ProductId = 2,
                            ProductImage = "images/bag-2.png",
                            ProductName = "Terra Bucket",
                            Quantity = 1,
                            SelectedColor = "Terracotta",
                            UnitPrice = 165.00m
                        });
                });

            modelBuilder.Entity("NehasBeed.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Badge")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Colors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("Reviews")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = "Bestseller",
                            Category = "Beaded bags",
                            Colors = "[\"Multicolor\",\"Earth Tones\",\"Blue Ocean\"]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A stunning handcrafted beaded tote bag featuring an intricate mosaic pattern. Each bead is meticulously placed by skilled artisans using premium Japanese Miyuki seed beads.",
                            Image = "images/bag-1.png",
                            Images = "[\"images/bag-1.png\",\"images/bag-2.png\"]",
                            InStock = true,
                            Name = "Mosaic Tote",
                            OriginalPrice = 220.00m,
                            Price = 185.00m,
                            Rating = 5.0m,
                            Reviews = 124,
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Badge = "New",
                            Category = "Beaded bags",
                            Colors = "[\"Terracotta\",\"Rust\",\"Sand\"]",
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A sophisticated bucket bag in warm terracotta tones. Handcrafted with thousands of premium seed beads creating a rich, textured surface.",
                            Image = "images/bag-2.png",
                            Images = "[\"images/bag-2.png\",\"images/bag-1.png\"]",
                            InStock = true,
                            Name = "Terra Bucket",
                            Price = 165.00m,
                            Rating = 4.8m,
                            Reviews = 54,
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Badge = "Sale",
                            Category = "Beaded bags",
                            Colors = "[\"Black\",\"Midnight\"]",
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An elegant evening clutch in classic noir. The deep black beads create a sophisticated pattern perfect for formal occasions.",
                            Image = "images/bag-3.png",
                            Images = "[\"images/bag-3.png\"]",
                            InStock = true,
                            Name = "Noir Clutch",
                            OriginalPrice = 175.00m,
                            Price = 145.00m,
                            Rating = 4.9m,
                            Reviews = 87,
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Badge = "Limited",
                            Category = "Beaded bags",
                            Colors = "[\"Pearl White\",\"Champagne\",\"Rose\"]",
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A luxurious mini bag adorned with pearlescent beads. The delicate sheen and feminine silhouette make this a truly special piece.",
                            Image = "images/bag-4.png",
                            Images = "[\"images/bag-4.png\",\"images/bag-5.png\"]",
                            InStock = true,
                            Name = "Pearl Mini",
                            Price = 210.00m,
                            Rating = 5.0m,
                            Reviews = 67,
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Category = "Beaded bags",
                            Colors = "[\"Floral Mix\",\"Pink Garden\",\"Sage Green\"]",
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A charming pouch featuring a delicate floral beaded design. Perfect for carrying your essentials with artistic flair.",
                            Image = "images/bag-5.png",
                            Images = "[\"images/bag-5.png\",\"images/bag-1.png\"]",
                            InStock = true,
                            Name = "Garden Pouch",
                            Price = 125.00m,
                            Rating = 4.7m,
                            Reviews = 43,
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Badge = "Bestseller",
                            Category = "Chain",
                            Colors = "[\"Gold\",\"Antique Gold\",\"Silver\"]",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A bold statement chain necklace featuring intricate gold-tone beadwork. Each link is handcrafted for a luxurious drape and finish.",
                            Image = "images/bag-3.png",
                            Images = "[\"images/bag-3.png\"]",
                            InStock = true,
                            Name = "Sovereign Chain",
                            OriginalPrice = 105.00m,
                            Price = 85.00m,
                            Rating = 4.9m,
                            Reviews = 98,
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Badge = "New",
                            Category = "Necklaces",
                            Colors = "[\"Onyx Black\",\"Charcoal\"]",
                            CreatedAt = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A multi-strand layered necklace featuring deep onyx seed beads. The layered effect creates a rich, textured look perfect for any occasion.",
                            Image = "images/bag-1.png",
                            Images = "[\"images/bag-1.png\"]",
                            InStock = true,
                            Name = "Onyx Layers",
                            Price = 95.00m,
                            Rating = 5.0m,
                            Reviews = 76,
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Category = "Earings",
                            Colors = "[\"Crystal Clear\",\"Rose Gold\",\"Sapphire\"]",
                            CreatedAt = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Delicate crystal bead earrings that catch the light beautifully. Lightweight yet statement-making, these earrings are perfect for day to evening wear.",
                            Image = "images/bag-4.png",
                            Images = "[\"images/bag-4.png\"]",
                            InStock = true,
                            Name = "Crystal Drops",
                            Price = 55.00m,
                            Rating = 4.8m,
                            Reviews = 112,
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NehasBeed.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NehasBeed.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NehasBeed.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NehasBeed.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NehasBeed.Models.Order", b =>
                {
                    b.HasOne("NehasBeed.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NehasBeed.Models.OrderItem", b =>
                {
                    b.HasOne("NehasBeed.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NehasBeed.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NehasBeed.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
